import type { Metadata } from "next";
import { Inter } from "next/font/google";
import I18NextProvider from "@/i18n/I18NextProvider";
import { Navbar } from "@/ui/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <I18NextProvider>
          <Navbar />
          {children}
        </I18NextProvider>
      </body>
    </html>
  );
}
